### PR TITLE
Library and Book Class Dependent method name Changes

### PR DESCRIPTION
**Pull request by BLakshmiPrasanna**

### CODE REVIEW

**Comment by BLakshmiPrasanna** [comment]
Hi @abhimaniac4  please review the above changes

**Comment by abhimaniac4** [comment]
requesting @iamharisali to review the changes made by @BLakshmiPrasanna

**Comment by BLakshmiPrasanna** [comment]
Hi @abhimaniac4  any updates

**Comment by abhimaniac4** [comment]
Hi @BLakshmiPrasanna have requested @iamharisali to review your commits. Waiting for a response

**Comment by iamharisali** [comment]
Everything looks good. Ok to merge

**Review by iamharisali — APPROVED** [review]

**Pull request merged**
