### PR TITLE
changes in "ReturnBookUI.java" and "ReturnBookControl.java" class

### PR DESCRIPTION
**Pull request by Lakshansm90**
hi @BLakshmiPrasanna ,

I have done some changes in the "ReturnBookUI.java" and "ReturnBookControl.java" classes, could you please ask @abhimaniac4  to review it.

Thanks,
Lakshan

### CODE REVIEW

**Comment by BLakshmiPrasanna** [comment]
Hi @abhimaniac4  please review  the changes done by Lakshan

**Comment by BLakshmiPrasanna** [comment]
hi @abhimaniac4  is there any update for review on changes

**Comment by Lakshansm90** [comment]
Hi @BLakshmiPrasanna,
Could you please follow up on this item.
Thanks,
Lakshan

**Review by abhimaniac4 — APPROVED** [review]
Your commits have been reviewed successfully @Lakshansm90

**Pull request merged**
