### PR TITLE
Changes to the Member class

### PR DESCRIPTION
**Pull request by Lakshansm90**
Hi @BLakshmiPrasanna ,
Could you ask @abhimaniac4 to review the work.
Thanks
Lakshan

### CODE REVIEW

**Comment by BLakshmiPrasanna** [comment]
Hi @abhimaniac4  Please review the above changes in member class

**Review by abhimaniac4 — APPROVED** [review]
Changes are approved @Lakshansm90 @BLakshmiPrasanna

**Comment by BLakshmiPrasanna** [comment]
Thanks for  reviewing @abhimaniac4  
@Lakshansm90  please merge the code

**Comment by BLakshmiPrasanna** [comment]
Closing the above raised issue its cleared by one of the collabrator

**Pull request merged**
