### PR TITLE
Changes in  returnBookControl class

### PR DESCRIPTION
**Pull request by Lakshansm90**
Hi @BLakshmiPrasanna,

I have done some changes in returnBookControl class. Could you please check.

Thanks,
Lakshan

### CODE REVIEW

**Comment by BLakshmiPrasanna** [comment]
Hi Abhimanyu,
Above code having changes about  variables and method names in return book control class that meeting entry criteria to proceed for review.
please review it by 19/8/2020
Thanks,
Lakshmi Prasanna.

**Comment by BLakshmiPrasanna** [comment]
Hi @abhimaniac4  please review the changes made by Lakshan 
Thanks

**Comment by abhimaniac4** [comment]
Changes are made correctly. @BLakshmiPrasanna

**Review by abhimaniac4 — COMMENTED** [review]
Changes are made correctly @Lakshansm90

**Comment by BLakshmiPrasanna** [comment]
Hi @Lakshansm90  As changes are reviewed and its correct to proceed no need to revert the code and make sure merge should happen only after review
Thanks

**Pull request merged**
